name: daviddrabik
static_sites:
- name: site
  github:
    repo: ddrabik/personal
    branch: main
    deploy_on_push: true
  environment_slug: node-js
  build_command: npm run build
  output_dir: dist
